# Generated by Django 6.0.6 on 2026-06-10 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Commune",
                "verbose_name_plural": "Communes",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Quartier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "commune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quartiers",
                        to="localisation.commune",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quartier",
                "verbose_name_plural": "Quartiers",
                "ordering": ["commune__nom", "nom"],
                "unique_together": {("commune", "nom")},
            },
        ),
    ]
