# Generated by Django 6.0.6 on 2026-06-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Signalement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("localisation", models.CharField(max_length=255)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("statut", models.CharField(default="en attente", max_length=50)),
            ],
        ),
    ]
