"""
Django settings for urbanalert project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k5w#rs8aig))b7eij6#!28eqtbi*+q+ouz)^am@ua(ti%=$dsq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # MES APPLICATIONS
    'utilisateurs',
    'signalements',
    'localisation',
    'interactions',
    'moderation',
    'rapports',
    'tableau_de_bord',
    'accueil',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'UrbanAlert.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Dossier templates global du projet (base.html et templates partagés)
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'UrbanAlert.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
     'default': {
          'ENGINE': 'django.db.backends.postgresql',
          'NAME': 'alert',
          'USER': 'postgres',
          'PASSWORD': '12345',
          'HOST': 'localhost',
          'PORT': '5432',
     }
 }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Interface en français (langue principale de la Guinée)
LANGUAGE_CODE = 'fr-fr'

# Fuseau horaire de Conakry (GMT+0)
TIME_ZONE = 'Africa/Conakry'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# ==============================
# MODELE UTILISATEUR PERSONNALISE
# ==============================

# Indique à Django que le modèle utilisateur principal
# du projet est le modèle Utilisateur
# situé dans l'application utilisateurs
AUTH_USER_MODEL = 'utilisateurs.Utilisateur'

# ==========================================
# CONFIGURATION DES FICHIERS MEDIA
# ==========================================

# URL utilisée dans le navigateur
# pour accéder aux fichiers uploadés
# Exemple :
# http://127.0.0.1:8000/media/profils/photo.jpg
MEDIA_URL = '/media/'


# Dossier physique où Django stockera
# les fichiers uploadés par les utilisateurs
# Exemple :
# UrbanAlert/media/
MEDIA_ROOT = BASE_DIR / 'media'